FROM --platform=linux/amd64 rust:1.83-alpine AS builder

ARG CATRACA_VERSION=v0.2.0

RUN apk add --no-cache musl-dev git

RUN cargo install \
    --git https://github.com/maracatu-labs/catraca \
    --tag ${CATRACA_VERSION} \
    --root /out \
    catraca

FROM scratch

COPY --from=builder /out/bin/catraca /lb

ENTRYPOINT ["/lb"]
