services:
  lb:
    image: ghcr.io/whereisanzi/rinha-lb:0d2f527
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - UPSTREAMS=/sockets/api1.sock,/sockets/api2.sock
      - BACKLOG=4096
      - HEALTH_PATH=/ready
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    networks:
      - rinha-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30M"

  api1:
    image: ghcr.io/whereisanzi/rinha-api:0d2f527
    environment:
      - INDEX_PATH=/resources/index.bin
      - UDS_PATH=/sockets/api1.sock
      - UDS_MODE=438
      - BACKLOG=4096
      - SEARCH=0
      - FAST_NPROBE=4
      - SCHED=other
    volumes:
      - sockets:/sockets
    networks:
      - rinha-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160M"

  api2:
    image: ghcr.io/whereisanzi/rinha-api:0d2f527
    environment:
      - INDEX_PATH=/resources/index.bin
      - UDS_PATH=/sockets/api2.sock
      - UDS_MODE=438
      - BACKLOG=4096
      - SEARCH=0
      - FAST_NPROBE=4
      - SCHED=other
    volumes:
      - sockets:/sockets
    networks:
      - rinha-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160M"
    depends_on:
      - api1

volumes:
  sockets:

networks:
  rinha-net:
    driver: bridge
